apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
    component: files-service
  template:
    metadata:
      labels:
        component: files-service
    spec:
      containers:
        - name: files-service
          image: vikramhemchandar/ytgratitudeapp:files-servicev1.0
          ports:
          - containerPort: 5004
          env:
            - name: PORT
              values: 5004
            - name: AWS_REGION
              values: "us-east-1"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          

  