apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: stats-service
    template:
      metadata:
        labels:
          component: stats-service
      spec:
        containers:
          - name: stats-service
            image: vikramhemchandar/ytgratitudeapp:stats-servicev1.0
            port:
              - containerPort: 50053
            env: 
              - name: HOST
                values: "0.0.0.0"
              - name: PORT
                values: "50053"
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"