apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
    component: stats-api
  template:
    metadata:
      labels:
        component: stats-api
    spec:
      containers:
        - name: stats-api
          image: vikramhemchandar/ytgratitudeapp:stats-apiv1.0
          ports:
            - containerPort: 5003
          env: 
            - name: STATS_SERVICE_ADDR
              values: "stats-service-cluster-ip-service:50053";
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"